[package]
name = "fb_server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
fb_shared.workspace = true
fb_sim.workspace = true
fb_maps.workspace = true
fb_arena.workspace = true
fb_net.workspace = true
bevy = { workspace = true, features = ["std", "bevy_log", "sysinfo_plugin"] }
clap.workspace = true
lightyear = { workspace = true, features = ["server", "std", "replication", "prediction", "interpolation", "input_native", "netcode", "udp", "websocket"] }

[lints]
workspace = true
