[package]
name = "fb_net"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
fb_shared.workspace = true
fb_proto.workspace = true
fb_sim.workspace = true
bevy = { workspace = true, features = ["std", "bevy_log"] }
bevy_replicon = { workspace = true, features = ["server"] }
clap.workspace = true
lightyear = { workspace = true, features = [
  "std",
  "replication",
  "prediction",
  "interpolation",
  "input_native",
  "netcode",
  "udp",
  "websocket",
] }
serde.workspace = true

[dev-dependencies]
bevy = { workspace = true, features = ["bevy_state"] }
lightyear = { workspace = true, features = ["server"] }
serde-reflection.workspace = true

[lints]
workspace = true
